# Generated by Django 4.2.27 on 2026-01-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="default_area",
        ),
        migrations.RemoveField(
            model_name="template",
            name="default_tags",
        ),
        migrations.RemoveField(
            model_name="template",
            name="user",
        ),
        migrations.DeleteModel(
            name="ImportJob",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
