# Generated by Django 4.2.27 on 2026-01-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0002_remove_template_default_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="imports/",
                verbose_name="Файл для импорта",
            ),
        ),
    ]
