# Generated by Django 4.2.27 on 2026-01-18 17:49

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0005_alter_source_source_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=config.storage.MediaMinIOStorage(),
                upload_to="info_sources/",
                verbose_name="Файл для импорта",
            ),
        ),
    ]
