FROM nginx:1.28.1-alpine AS builder

ENV MODSECURITY_VERSION=v3.0.14
ENV MODSECURITY_NGINX_VERSION=v1.0.4

RUN apk add --no-cache --virtual .build-deps \
        alpine-sdk \
        autoconf \
        automake \
        bison \
        curl \
        doxygen \
        flex \
        g++ \
        gcc \
        git \
        libtool \
        lmdb-dev \
        lua5.4-dev \
        make \
        curl-dev \
        pcre2-dev \
        yajl-dev \
        zlib-dev \
        libxml2-dev \
        geoip-dev \
        pcre-dev \
        linux-headers \
        wget

WORKDIR /opt

RUN wget https://nginx.org/download/nginx-1.28.1.tar.gz \
    && tar -xzf nginx-1.28.1.tar.gz \
    && rm nginx-1.28.1.tar.gz

RUN git clone --depth 1 -b ${MODSECURITY_VERSION} https://github.com/owasp-modsecurity/ModSecurity.git

RUN git clone --depth 1 -b ${MODSECURITY_NGINX_VERSION} https://github.com/owasp-modsecurity/ModSecurity-nginx.git

RUN cd /opt/ModSecurity \
    && git submodule init \
    && git submodule update \
    && sed -i '/#include <memory>/a #include <cstdint>' \
       headers/modsecurity/collection/collection.h \
    && ./build.sh \
    && ./configure --prefix=/usr/local/modsecurity --with-lmdb --with-pcre2 \
    && make \
    && make install \
    && make clean

RUN cd /opt/nginx-1.28.1 \
    && ./configure --with-compat --add-dynamic-module=/opt/ModSecurity-nginx \
    && make modules \
    && cp objs/ngx_http_modsecurity_module.so /etc/nginx/modules \
    && mkdir -p /etc/nginx/modsec \
    && cp /opt/ModSecurity/unicode.mapping /etc/nginx/modsec/

FROM nginx:1.28.1-alpine AS final

RUN apk add --no-cache --virtual .runtime-deps \
        lua5.4 \
        yajl \
        libstdc++ \
        pcre2 \
        lmdb \
        geoip \
        libxml2 \
        curl

RUN mkdir -p /etc/nginx/modules-available \
    && echo "load_module modules/ngx_http_modsecurity_module.so;" > /etc/nginx/modules-available/50-modsecurity.conf \
    && mkdir -p /etc/nginx/modules-enabled \
    && ln -s /etc/nginx/modules-available/50-modsecurity.conf /etc/nginx/modules-enabled/
COPY --from=builder /usr/local/modsecurity/ /usr/local/modsecurity/
COPY --from=builder /etc/nginx/modules/ngx_http_modsecurity_module.so /etc/nginx/modules/
COPY --from=builder /etc/nginx/modsec/unicode.mapping /etc/nginx/modsec/

LABEL maintainer="deadwood project proxy <nothing@fuck.off>" \
      nginx_version="1.28.1" \
      modsecurity_version="v3.0.14" \
      modsecurity_nginx_version="v1.0.4"
