# Generated by Django 4.2.27 on 2026-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_dailymetric_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="exercises",
            field=models.TextField(
                blank=True, null=True, verbose_name="Упражнения (JSON или текст)"
            ),
        ),
    ]
